//! Host<->device request/response messages (the USB-CDC protocol payloads).
//!
//! Each message encodes as a flat CBOR array led by an integer tag: `[tag, ...fields]`.
//! `Request` (host -> device) and `Response` (device -> host) are separate enums with
//! separate tag spaces; the body bytes travel inside a frame (see the `frame` module).
//! Text fields are printable-ASCII (F15); byte fields borrow the input, zero-copy, like
//! the COSE and manifest types.

use crate::{alg::AlgId, ascii::AsciiStr, error::ErrorCode};

/// Maximum number of algorithm identifiers carried in an `Info` list.
pub const MAX_ALGS: usize = 8;

/// A bounded, heap-free list of algorithm identifiers.
pub type AlgList = heapless::Vec<AlgId, MAX_ALGS>;

/// A request from host to device.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Request {
    /// Report device capabilities (`-> Response::Info`).
    GetInfo,
    /// Generate the signing and KEM key pairs (`-> Response::PublicKeys`).
    InitKeys { sig_alg: AlgId, kem_alg: AlgId },
}

/// A response from device to host.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Response<'b> {
    /// Device capabilities and current state.
    Info {
        /// Firmware version string.
        fw: AsciiStr<'b>,
        /// Supported signature algorithms.
        sig_algs: AlgList,
        /// Supported KEM algorithms.
        kem_algs: AlgList,
        /// Whether the device key pairs have been generated.
        keys_present: bool,
        /// Whether the entropy source is currently healthy.
        entropy_healthy: bool,
    },
    /// The public keys generated by `InitKeys`.
    PublicKeys {
        /// Algorithm of the signing public key.
        sig_alg: AlgId,
        /// The signing public key bytes.
        sig_public_key: &'b [u8],
        /// Algorithm of the KEM public key.
        kem_alg: AlgId,
        /// The KEM public key bytes.
        kem_public_key: &'b [u8],
    },
    /// An error reply.
    Error {
        /// The error code.
        code: ErrorCode,
        /// A human-readable detail string (may be empty).
        detail: AsciiStr<'b>,
    },
}
